///////////////////////////////////////////////////////////
//  Database.cs
//  Implementation of the Class Database
//  Generated by Enterprise Architect
//  Created on:      06-May-2023 12:08:54 AM
//  Original author: Meysam
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace source {
	public class Database {

		public Database(){

		}

		~Database(){

		}

		/// 
		/// <param name="self"></param>
		/// <param name="root_directory"></param>
		public void __init__(self, root_directory){

		}

		/// 
		/// <param name="self"></param>
		public void load_database(self){

		}

		/// 
		/// <param name="self"></param>
		public void save_database(self){

		}

	}//end Database

}//end namespace source