#######################################################
# 
# Doctor.py
# Python implementation of the Class Doctor
# Generated by Enterprise Architect
# Created on:      06-May-2023 12:08:55 AM
# Original author: Meysam
# 
#######################################################


class Doctor(object):
    def __init__(self, name, lastname, doctor_id, username, password):
        pass