#######################################################
# 
# Medicine.py
# Python implementation of the Class Medicine
# Generated by Enterprise Architect
# Created on:      06-May-2023 12:08:55 AM
# Original author: Meysam
# 
#######################################################


class Medicine:
    def __init__(self, medicines_list):
        pass

    def exist_medicine(self, medicine_name):
        pass

    def index_of_medicine(self, medicine_name):
        pass

    def add_medicine(self, name, dos, max_dos, min_dos):
        pass

    def edit_medicine(self, medicine_name, newname, dos, max_dos, min_dos):
        pass

    def search_medicine(self, medicine_name):
        pass

    def show_medicine_info(self, index_of_patient):
        pass

    def delete_medicine(self, medicine_name):
        pass