#######################################################
# 
# Patient.py
# Python implementation of the Class Patient
# Generated by Enterprise Architect
# Created on:      06-May-2023 12:08:55 AM
# Original author: Meysam
# 
#######################################################


class Patient:
    def __init__(self, patients_accounts):
        pass

    def exist_patient(self, national_code):
        pass

    def create_new_patient_account(self, name, lastname, national_code, birth_date, father_name):
        pass

    def index_of_patient(self, national_code):
        pass

    def search_patient_account(self, national_code):
        pass

    def edit_patient_account(self, national_code, name, lastname, birthdate, father_name):
        pass

    def show_patient_account(self, index_of_patient):
        pass

    def delete_patient_account(self, national_code):
        pass