#######################################################
# 
# Visit.py
# Python implementation of the Class Visit
# Generated by Enterprise Architect
# Created on:      06-May-2023 12:08:55 AM
# Original author: Meysam
# 
#######################################################
from source.Patient import Patient

class Visit(Patient):
    def __init__(self, patients_accounts, medicines_list, patient_medicine_list):
        pass

    def report(self, patient_national_code):
        pass

    def previous_prescriptions(self, patient_national_code):
        pass

    def prescribe_from_medicines_list(self, input_char):
        pass